mkdir -p "$MODPATH/config/properties"
touch "$MODPATH/config/properties/ro.product.mod_device"
echo -n "CN" >"$MODPATH/config/properties/ro.miui.region"
echo -n "cn" >"$MODPATH/config/properties/ro.miui.cust_variant"
echo -n "9460" >"$MODPATH/config/properties/ro.miui.mcc"
echo -n "zh-CN" >"$MODPATH/config/properties/ro.product.locale"
echo -n "CN" >"$MODPATH/config/properties/ro.product.locale.region"
echo -n "cn" >"$MODPATH/config/properties/ro.product.locale.language"

mkdir -p "$MODPATH/config/packages"
#contacts && mms
touch "$MODPATH/config/packages/com.android.contacts"
touch "$MODPATH/config/packages/com.android.mms"
touch "$MODPATH/config/packages/com.xiaomi.aiasst.service"
touch "$MODPATH/config/packages/com.miui.yellowpage"

touch "$MODPATH/config/packages/com.android.calendar"
touch "$MODPATH/config/packages/com.miui.virtualsim"
touch "$MODPATH/config/packages/com.miui.notification"
touch "$MODPATH/config/packages/com.miui.translationservice"
touch "$MODPATH/config/packages/com.miui.contentextension"
touch "$MODPATH/config/packages/com.miui.personalassistant"
touch "$MODPATH/config/packages/com.miui.contentcatcher"
